name: update_notification
description: Check if the user has recent version of your Flutter app.
version: 1.0.1
homepage: https://github.com/d2itechnology/update_notification

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^2.0.2
  html: ^0.15.0
  url_launcher: ^6.0.11
  collection: ^1.15.0
  http: ^0.13.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

assets:
    - assets/images/  

 
